import json
from pathlib import Path
from typing import Iterable

import numpy as np
import torch
from transformers import AutoModel, AutoTokenizer

BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
VIDEOS_DIR = RAW_DIR / "videos"
ARTICLES_DIR = RAW_DIR / "articles"
INDEX_DIR = PROJECT_ROOT / "data" / "processed"
INDEX_DIR.mkdir(parents=True, exist_ok=True)

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
CHUNK_SIZE_WORDS = 180
CHUNK_OVERLAP_WORDS = 40
BATCH_SIZE = 32
MAX_LENGTH = 512


def iter_text_files(paths: Iterable[Path]) -> Iterable[Path]:
    for folder in paths:
        if folder.exists():
            yield from sorted(folder.glob("*.txt"))


def load_clean_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="ignore").strip()
    if not text:
        return ""
    # Skip placeholder error files generated by extractors.
    if text.startswith("[ERROR]"):
        return ""
    return text


def parse_document(path: Path) -> dict | None:
    raw_text = load_clean_text(path)
    if not raw_text:
        return None

    lines = raw_text.splitlines()
    metadata: dict[str, str] = {
        "title": "",
        "author": "",
        "website": "",
        "url": "",
        "type": "",
    }
    expected_keys = {
        "TITLE": "title",
        "AUTHOR": "author",
        "WEBSITE": "website",
        "URL": "url",
        "TYPE": "type",
    }

    header_complete = len(lines) >= 6
    if header_complete:
        for idx, key in enumerate(expected_keys):
            line = lines[idx]
            prefix = f"{key}:"
            if not line.startswith(prefix):
                header_complete = False
                break
            metadata[expected_keys[key]] = line[len(prefix) :].strip()

    if header_complete:
        body = "\n".join(lines[6:]).strip()
    else:
        body = raw_text

    if not body:
        return None

    return {
        "text": body,
        "metadata": metadata,
    }


def chunk_text(text: str, chunk_size: int, overlap: int) -> list[str]:
    words = text.split()
    if not words:
        return []

    chunks: list[str] = []
    step = max(1, chunk_size - overlap)
    for i in range(0, len(words), step):
        chunk_words = words[i : i + chunk_size]
        if not chunk_words:
            continue
        chunks.append(" ".join(chunk_words))
        if i + chunk_size >= len(words):
            break
    return chunks


def compute_embeddings(
texts: list[str], model: AutoModel, tokenizer: AutoTokenizer, device: str, batch_size: int
) -> np.ndarray:
    """
    Compute dense embeddings for a list of texts.

    Uses masked mean pooling over last_hidden_state and L2-normalizes vectors.
    Returns a float32 numpy array of shape (len(texts), embedding_dim).
    """
    all_embeddings: list[np.ndarray] = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i : i + batch_size]
        inputs = tokenizer(
            batch_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=MAX_LENGTH,
        ).to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            hidden_states = outputs.last_hidden_state
            attention_mask = inputs["attention_mask"].unsqueeze(-1).expand(hidden_states.size()).float()
            masked_hidden = hidden_states * attention_mask
            sum_hidden = masked_hidden.sum(dim=1)
            mask_sum = attention_mask.sum(dim=1).clamp(min=1e-9)
            embedding = sum_hidden / mask_sum
            embedding = torch.nn.functional.normalize(embedding, p=2, dim=1)

        all_embeddings.append(embedding.cpu().numpy().astype("float32"))

    return np.vstack(all_embeddings)


def main() -> None:
    files = list(iter_text_files([VIDEOS_DIR, ARTICLES_DIR]))
    if not files:
        print("[ERROR] No .txt files found in raw/videos or raw/articles")
        return

    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer = AutoTokenizer.from_pretrained(EMBED_MODEL)
    model = AutoModel.from_pretrained(EMBED_MODEL).to(device)
    model.eval()

    chunk_records: list[dict] = []
    chunk_texts: list[str] = []

    for file_path in files:
        document = parse_document(file_path)
        if not document:
            print(f"[SKIP] {file_path.name} has empty/error text")
            continue

        text = document["text"]
        metadata = document["metadata"]

        chunks = chunk_text(text, CHUNK_SIZE_WORDS, CHUNK_OVERLAP_WORDS)
        for idx, chunk in enumerate(chunks):
            chunk_records.append(
                {
                    "chunk_id": len(chunk_records),
                    "source_file": str(file_path.relative_to(BASE_DIR)),
                    "source_name": file_path.name,
                    "chunk_index": idx,
                    "title": metadata["title"],
                    "author": metadata["author"],
                    "website": metadata["website"],
                    "url": metadata["url"],
                    "type": metadata["type"],
                    "text": chunk,
                }
            )
            chunk_texts.append(chunk)

    if not chunk_texts:
        print("[ERROR] No valid text chunks were produced")
        return

    print(f"[INFO] Encoding {len(chunk_texts)} chunks with {EMBED_MODEL} on {device}")
    embeddings = compute_embeddings(
        texts=chunk_texts,
        model=model,
        tokenizer=tokenizer,
        device=device,
        batch_size=BATCH_SIZE,
    )

    np.save(INDEX_DIR / "embeddings.npy", embeddings)
    with open(INDEX_DIR / "chunks.json", "w", encoding="utf-8") as f:
        json.dump(chunk_records, f, ensure_ascii=True, indent=2)

    config = {
        "embed_model": EMBED_MODEL,
        "device": device,
        "chunk_size_words": CHUNK_SIZE_WORDS,
        "chunk_overlap_words": CHUNK_OVERLAP_WORDS,
        "batch_size": BATCH_SIZE,
        "max_length": MAX_LENGTH,
        "num_files": len(files),
        "num_chunks": len(chunk_records),
        "embeddings_file": "embeddings.npy",
        "metadata_file": "chunks.json",
    }
    with open(INDEX_DIR / "index_config.json", "w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=True, indent=2)

    print(f"[DONE] Saved embeddings to {INDEX_DIR / 'embeddings.npy'}")
    print(f"[DONE] Saved chunk metadata to {INDEX_DIR / 'chunks.json'}")


if __name__ == "__main__":
    main()
